package se.hig.aod.projekt;

/**
 * Exception generated by the lisp parser
 *
 * @author Viktor Hanstorp (ndi14vhp@student.hig.se)
 */
@SuppressWarnings("serial")
public class LispException extends RuntimeException
{
    LispException()
    {
    }

    LispException(String msg)
    {
        super(msg);
    }
}